name: fluttery
description: Flutter package that helps with prototyping.
version: 0.0.5
author: Matt Carroll
homepage: https://github.com/matthew-carroll/fluttery

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0